config/routes.rb
Rails.application.routes.draw do
  resources :checklist_items
  resources :checklists
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist.rb
class Checklist < ApplicationRecord
  belongs_to :user
  has_many :checklist_items

  accepts_nested_attributes_for :checklist_items, :allow_destroy => true, :reject_if => :all_blank
end

app/models/checklist_item.rb
class ChecklistItem < ApplicationRecord
  belongs_to :checklist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :checklists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    checklists_path
  end
end

app/controllers/checklist_items_controller.rb
class ChecklistItemsController < ApplicationController
  before_action :set_checklist_item, only: [:show, :edit, :update, :destroy]

  # GET /checklist_items
  def index
    @checklist_items = ChecklistItem.all
  end

  # GET /checklist_items/1
  def show
  end

  # GET /checklist_items/new
  def new
    @checklist_item = ChecklistItem.new
  end

  # GET /checklist_items/1/edit
  def edit
  end

  # POST /checklist_items
  def create
    @checklist_item = ChecklistItem.new(checklist_item_params)

    if @checklist_item.save
      redirect_to @checklist_item, notice: 'Checklist item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /checklist_items/1
  def update
    if @checklist_item.update(checklist_item_params)
      redirect_to @checklist_item, notice: 'Checklist item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /checklist_items/1
  def destroy
    @checklist_item.destroy
    redirect_to checklist_items_url, notice: 'Checklist item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checklist_item
      @checklist_item = ChecklistItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def checklist_item_params
      params.require(:checklist_item).permit(:content, :is_checked)
    end
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_checklist, only: [:show, :edit, :update, :destroy]

  # GET /checklists
  def index
    @checklists = current_user.checklists
  end

  # GET /checklists/1
  def show
  end

  # GET /checklists/new
  def new
    @checklist = current_user.checklists.new  #Checklist.new
  end

  # GET /checklists/1/edit
  def edit
  end

  # POST /checklists
  def create
    @checklist = Checklist.new(checklist_params)

    if @checklist.save
      redirect_to @checklist, notice: 'Checklist was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /checklists/1
  def update
    if @checklist.update(checklist_params)
      redirect_to @checklist, notice: 'Checklist was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /checklists/1
  def destroy
    @checklist.destroy
    redirect_to checklists_url, notice: 'Checklist was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checklist
      @checklist = Checklist.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def checklist_params
      params.require(:checklist).permit(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checklist_items/_form.html.erb
<%= form_with(model: checklist_item, local: true) do |form| %>
  <% if checklist_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(checklist_item.errors.count, "error") %> prohibited this checklist_item from being saved:</h2>

      <ul>
      <% checklist_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :checklist_item_content %>
  </div>

  <div class="field">
    <%= form.label :is_checked %>
    <%= form.check_box :is_checked, id: :checklist_item_is_checked %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/checklist_items/edit.html.erb
<h1>Editing Checklist Item</h1>

<%= render 'form', checklist_item: @checklist_item %>

<%= link_to 'Show', @checklist_item %> |
<%= link_to 'Back', checklist_items_path %>

app/views/checklist_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Checklist Items</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Is checked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checklist_items.each do |checklist_item| %>
      <tr>
        <td><%= checklist_item.content %></td>
        <td><%= checklist_item.is_checked %></td>
        <td><%= link_to 'Show', checklist_item %></td>
        <td><%= link_to 'Edit', edit_checklist_item_path(checklist_item) %></td>
        <td><%= link_to 'Destroy', checklist_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checklist Item', new_checklist_item_path %>

app/views/checklist_items/new.html.erb
<h1>New Checklist Item</h1>

<%= render 'form', checklist_item: @checklist_item %>

<%= link_to 'Back', checklist_items_path %>

app/views/checklist_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @checklist_item.content %>
</p>

<p>
  <strong>Is checked:</strong>
  <%= @checklist_item.is_checked %>
</p>

<%= link_to 'Edit', edit_checklist_item_path(@checklist_item) %> |
<%= link_to 'Back', checklist_items_path %>

app/views/checklists/_form.html.haml
= form_with(model: checklist, local: true) do |form|
  - if checklist.errors.any?
    #error_explanation
      %h2
        = pluralize(checklist.errors.count, "error") 
        prohibited this checklist from being saved:

      %ul
        - checklist.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :title
    = form.text_field :title, id: :checklist_title

  = form.fields_for :checklist_items do |checklist_item_fields|
    = checklist_item_fields.text_field :content

  .actions
    = form.submit

app/views/checklists/edit.html.erb
<h1>Editing Checklist</h1>

<%= render 'form', checklist: @checklist %>

<%= link_to 'Show', @checklist %> |
<%= link_to 'Back', checklists_path %>

app/views/checklists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Checklists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checklists.each do |checklist| %>
      <tr>
        <td><%= checklist.title %></td>
        <td><%= link_to 'Show', checklist %></td>
        <td><%= link_to 'Edit', edit_checklist_path(checklist) %></td>
        <td><%= link_to 'Destroy', checklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checklist', new_checklist_path %>

app/views/checklists/new.html.erb
<h1>New Checklist</h1>

<%= render 'form', checklist: @checklist %>

<%= link_to 'Back', checklists_path %>

app/views/checklists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @checklist.title %>
</p>

<%= link_to 'Edit', edit_checklist_path(@checklist) %> |
<%= link_to 'Back', checklists_path %>

app/views/home/index.haml
%h1 We're in business!!

app/views/layouts/_flash.html.haml
- if notice
  %p.notice= notice
- if alert
  %p.alert= alert

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-light.bg-faded
  %button.navbar-toggler.navbar-toggler-right{:type => 'button', :data => {:toggle => 'collapse', :target => '#navbar-toggle-yaca'}}
    %span.navbar-toggler-icon
  = link_to "YACA", '#', :class => 'navbar-brand'

  #navbar-toggle-yaca.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        = link_to 'Home', '#'
      %li.nav-item
        = render 'layouts/navbar/sign_in'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YACA - Yet Another Checklist App</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%-#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%-#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
    <%= javascript_pack_tag "hello_react" %>
    <%= stylesheet_pack_tag "yaca-app" %>
    <%= yield :javascript_packs %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <%= render 'layouts/nav' %>

    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= yield :javascripts %>
  </body>
</html>

app/views/layouts/navbar/_sign_in.html.haml
- if user_signed_in?
  = link_to 'Sign out', destroy_user_session_path, :method => :delete
- else
  = link_to 'Sign in/Sign up', new_user_session_path